ValidationSample/ValidationSample/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ValidationDAL;
using ValidationSample.Repository;
using System.Linq.Dynamic;
using System.Web.Script.Serialization;
namespace ValidationSample.Controllers
{
    public class MainController : Controller
    {
        ValidationRepository dal = new ValidationRepository();
        
        public ActionResult MainView()
        {
           
            
            if (Session["Id"] == null || Session["IsValid2FA"] == null || !(bool)Session["IsValid2FA"])
            {
                return RedirectToAction("Login", "Home");
            }
            return View();

        }

        public ActionResult GetAllEvents()
        {
            if(Session["id"]==null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View("GetAllEventsKendo");
        }


        public JsonResult GetEvents()
        {
            ValidationMapper<Event, Models.Event> mapObj = new ValidationMapper<Event, Models.Event>();

            var lstEvent = dal.GetEvents();
            List<Models.Event> lstModelEvent = new List<Models.Event>();
            if (lstEvent.Any())
            {
                foreach (var event1 in lstEvent)
                {
                    lstModelEvent.Add(mapObj.Translate(event1));
                }
            }
            foreach(var event1 in lstModelEvent)
            {
                event1.RecurrencePattern = event1.Recurrence + ";" + event1.RecurrenceInterval + ";" + event1.RecurrenceCount;
            }
            if (Session["Id"] != null)
            {
                string name = Session["Id"].ToString();
                ViewBag.name = name;
                
                return new JsonResult { Data = lstModelEvent , JsonRequestBehavior= JsonRequestBehavior.AllowGet };
                
            }
            else
            {
                return Json("Login");
            }
        }
        public JsonResult GetTestcaseLogs()
        {
            ValidationMapper<TestCaseLog, Models.TestCaseLog> mapObj = new ValidationMapper<TestCaseLog, Models.TestCaseLog>();

            var lstTestcaseLogs = dal.GetAllTestCaseLogs();
            List<Models.TestCaseLog> lstModelTestcaseLogs = new List<Models.TestCaseLog>();
            if (lstTestcaseLogs.Any())
            {
                foreach (var log1 in lstTestcaseLogs)
                {
                    lstModelTestcaseLogs.Add(mapObj.Translate(log1));
                }
            }
            
            if (Session["Id"] != null)
            {
                string name = Session["Id"].ToString();
                ViewBag.name = name;

                var jsonResult= new JsonResult { Data = lstModelTestcaseLogs, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            else
            {
                return Json("Login");
            }
        }
        
        public JsonResult GetTestcaseLogs2(int pageNumber, int pageSize)
        {
            ValidationMapper<TestCaseLog, Models.TestCaseLog> mapObj = new ValidationMapper<TestCaseLog, Models.TestCaseLog>();

            var lstTestcaseLogs = dal.GetTestcaseLogs(pageNumber,pageSize);
            List<Models.TestCaseLog> lstModelTestcaseLogs = new List<Models.TestCaseLog>();
            if (lstTestcaseLogs.Any())
            {
                foreach (var log1 in lstTestcaseLogs)
                {
                    lstModelTestcaseLogs.Add(mapObj.Translate(log1));
                }
            }
            //JavaScriptSerializer js = new JavaScriptSerializer();
            //js.Serialize(lstModelTestcaseLogs);
            var jsonResult = new JsonResult { Data = lstModelTestcaseLogs, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        [HttpGet]
        public JsonResult GetTestcaseLogsReact(string sortColumnName = "TestCaseLogId", string sortOrder = "asc", int pageSize = 50, int currentPage = 1)
        {
            ValidationMapper<TestCaseLog, Models.TestCaseLog> mapObj = new ValidationMapper<TestCaseLog, Models.TestCaseLog>();
            int totalPage = 0;
            int totalRecord = 0;
            var lstTestcaseLogs = dal.GetAllTestCaseLogs();
            List<Models.TestCaseLog> lstModelTestcaseLogs = new List<Models.TestCaseLog>();
            List<Models.TestCaseLog> List = new List<Models.TestCaseLog>();
            if (lstTestcaseLogs.Any())
            {
                foreach (var log1 in lstTestcaseLogs)
                {
                    lstModelTestcaseLogs.Add(mapObj.Translate(log1));
                }
            }
            totalRecord = lstModelTestcaseLogs.Count();
            if (pageSize > 0)
            {
                totalPage = totalRecord / pageSize + ((totalRecord % pageSize) > 0 ? 1 : 0);
                List = lstModelTestcaseLogs.OrderBy(sortColumnName + " " + sortOrder).Skip(pageSize * (currentPage - 1)).Take(pageSize).ToList();
            }
            else
            {
                List = lstModelTestcaseLogs.ToList();
            }
            
                

                var jsonResult = new JsonResult { Data = new { List = List, totalPage = totalPage, sortColumnName = sortColumnName, sortOrder = sortOrder, currentPage = currentPage },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;         
            
        }

        public JsonResult GetTestcaseLogData(int page)
        {
            ValidationMapper<TestCaseLog, Models.TestCaseLog> mapObj = new ValidationMapper<TestCaseLog, Models.TestCaseLog>();
            List<Models.TestCaseLog> lstModelTestcaseLogs = new List<Models.TestCaseLog>();
            List<Models.TestCaseLog> lstModelTestcaseLogs2 = new List<Models.TestCaseLog>();
            int totalPage = 0;
            int totalRecord = 0;
            int pageSize = 50;
            var lstTestcaseLogs = dal.GetAllTestCaseLogs().OrderBy(a=>a.TestCaseLogId).ToList();
            totalRecord = lstTestcaseLogs.Count;
            totalPage = (totalRecord / pageSize) + ((totalRecord % pageSize) > 0 ? 1 : 0);
            if (lstTestcaseLogs.Any())
            {
                foreach (var log1 in lstTestcaseLogs)
                {
                    lstModelTestcaseLogs.Add(mapObj.Translate(log1));
                }
            }
            lstModelTestcaseLogs2=lstModelTestcaseLogs.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            return new JsonResult { Data = new { List = lstModelTestcaseLogs2, currentPage = page, totalPage = totalPage }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public ActionResult GetAllTestcaseLogs()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View("GetAllTestcaseLogsReact");
        }
        [HttpPost]
        public JsonResult SaveEvent(Models.Event e1)
        {
            bool status = false;
            try
            {
                //if (e1.Recurrence == null)
                //{
                //    e1.Recurrence = "Single Day";
                //}
                ValidationMapper<Models.Event, Event> mapObj = new ValidationMapper<Models.Event, Event>();
               
                
                var event1 = dal.GetEvents().Where(a => a.EventId == e1.EventId).FirstOrDefault();
                if(event1!=null)
                {
                                               
                    event1 = mapObj.Translate(e1);
                    status = dal.EditEvent(event1);
                }
                
                
            }
            catch(Exception e)
            {
                status = false;
            }

            return new JsonResult { Data = new { status = status, JsonRequestBehavior = JsonRequestBehavior.AllowGet } };
        }
        public JsonResult AddEvent(Models.Event e1)
        {
            bool status = false;
            try
            {
                //if (e1.Recurrence == null)
                //{
                //    e1.Recurrence = "Single Day";
                //}
                ValidationMapper<Models.Event, Event> mapObj = new ValidationMapper<Models.Event, Event>();
                var event1 = mapObj.Translate(e1);
                status = dal.CreateEvent(event1);




            }
            catch (Exception e)
            {
                status = false;
            }

            return new JsonResult { Data = new { status = status, JsonRequestBehavior = JsonRequestBehavior.AllowGet } };
        }
        [HttpPost]
        public JsonResult DeleteEvent(int eventId)
        {
            bool status = false;
            try
            {
                var event1 = dal.GetEvents().Where(a => a.EventId == eventId).FirstOrDefault();
                if(event1!=null)
                {
                    status = dal.DeleteEvent(event1);
                }
            }
            catch(Exception e)
            {
                status = false;
            }

            return new JsonResult { Data = new { status = status, JsonRequestBehavior = JsonRequestBehavior.AllowGet } };
        }
       
        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetNotificationEvents()
        {
            var notificationRegisterTime = Session["LastUpdated"] != null ? Convert.ToDateTime(Session["LastUpdated"]) : DateTime.Now;

ValidationSample/ValidationSample/Views/Shared/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h3 style="color:green">@TempData["update"];</h3>

@Html.ActionLink("Go To Home", "GetAllTestCases", "Home");

ValidationSample/ValidationSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Validation</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body style="background-image : url(/Content/img/MainLayout.jpg)">
    
    
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: rgba(255,255,255,0.5);" data-target="#myNavbar">
        
        <div class="container">
            
            <div class="navbar-header">
                @*<span onclick="openNav()" style="font-size:30px;cursor:pointer">&#9776;</span>*@
                @Html.ActionLink("Home", "MainView", "Main", new { area = "" }, new { style = "color:green;" , @class = "navbar-brand" })
                <span class="noti glyphicon glyphicon-bell"><span class="count">&nbsp;</span></span>
                <div class="noti-content">
                    <div class="noti-top-arrow"></div>
                    <ul id="notiContent"></ul>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Home", "GetAllTestCases", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

               
            </div>
            @*<div id="mySidenav" class="sidenav"  >
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="#">About</a>
                <a href="#">Services</a>
                <a href="#">Clients</a>
                <a href="#">Contact</a>
                
                    <li>
                        <a><span class="ui-icon ui-icon-disk"></span>Save</a>
                    </li>
                    <li>
                        <div><span class="ui-icon ui-icon-zoomin"></span>Zoom In</div>
                    </li>
                    <li>
                        <div><span class="ui-icon ui-icon-zoomout"></span>Zoom Out</div>
                    </li>
                    <li class="ui-state-disabled">
                        <div><span class="ui-icon ui-icon-print"></span>Print...</div>
                    </li>
                    <ul>
                        <div>Playback</div>
                        
                            <li>
                                <div><span class="ui-icon ui-icon-seek-start"></span>Prev</div>
                            </li>
                            <li>
                                <div><span class="ui-icon ui-icon-stop"></span>Stop</div>
                            </li>
                            <li>
                                <div><span class="ui-icon ui-icon-play"></span>Play</div>
                            </li>
                            <li>
                                <div><span class="ui-icon ui-icon-seek-end"></span>Next</div>
                            </li>
                        
                    </ul>
                    <li>
                        <div>Learn more about this menu</div>
                    </li>
                
            </div>*@
            
            @if (Session["Id"] != null && Session["IsValid2FA"] != null && Convert.ToBoolean(Session["IsValid2FA"]))
            {
                <div class="collapse navbar-collapse " id="myNavbar">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Events", "GetAllEvents", "Main", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("TestSuite", "GetAllTestSuites", "TestSuite", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("TestcaseLog", "GetAllTestcaseLogs", "Main", new { area = "" }, new { @class = "navbar-brand" })
                        @*<span style="padding-left:800px; color: grey" class="navbar-brand">
                                @Html.ActionLink("Logout", "LogOut", "Home", new { style="color:grey;" })
                            </span>*@
                        <li class="w3-dropdown-hover w3-hide-small">
                            <button class="w3-padding-large w3-button" title="More" style="padding-left:300px; color: green; text-align:right"><b>@Session["Id"]</b> <i class="fa fa-caret-down" style="color: grey;align-content:flex-end"></i></button>
                            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                                @Html.ActionLink("Logout", "LogOut", "Home", new { @class = "w3-bar-item w3-button", style = "color:green;" })

                            </div>
                        </li>
                    </ul>
                </div>

            }



        </div>
    </div>

    <div class="body-content" id="main">
        <hr />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Validation</p>
        </footer>
    </div>


    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.js"></script>*@
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="/signalr/hubs"></script>
    @*<script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
    <style type="text/css">
        .ui-menu { width: 150px; }
        .noti-content {
            position: fixed;
            right: 100px;
            background: #e5e5e5;
            border-radius: 4px;
            top: 47px;
            width: 250px;
            display: none;
            border: 1px solid #9E988B;
        }

        ul#notiContent {
            max-height: 200px;
            overflow: auto;
            padding: 0px;
            margin: 0px;
            padding-left: 20px;
        }

            ul#notiContent li {
                margin: 3px;
                padding: 6px;
                background: #fff;
            }

        .noti-top-arrow {
            border-color: transparent;
            border-bottom-color: #F5DEB3;
            border-style: dashed dashed solid;
            border-width: 0 8.5px 8.5px;
            position: absolute;
            right: 32px;
            top: -8px;
        }

        span.noti {
            color: #FF2323;
            margin: 15px;
            position: fixed;
            right: 100px;
            font-size: 18px;
            cursor: pointer;
        }

        span.count {
            position: relative;
            top: -3px;
        }

        .sidenav {
            height: 100%; /* 100% Full-height */
            width: 0; /* 0 width - change this with JavaScript */
            position: fixed; /* Stay in place */
            z-index: 1; /* Stay on top */
            top: 0;
            left: 0;
            background-color: white; /* Black*/
            overflow-x: hidden; /* Disable horizontal scroll */
            padding-top: 60px; /* Place content 60px from the top */
            transition: 0.5s; /* 0.5 second transition effect to slide in the sidenav */
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: #818181;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover, .offcanvas a:focus {
                    color: #f1f1f1;
                }

            /* Position and style the close button (top right corner) */
            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding: 20px;
        }
    </style>
    
    <script type="text/javascript">
        function openNav() {
            
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
        $(function () {
            
            //$("#mySidenav").menu();
            $('span.noti').click(function (e) {
                e.stopPropagation();
                $('.noti-content').show();
                var count = 0;
                count = parseInt($('span.count').html()) || 0;
                
                if (count > 0) {
                    updateNotification();
                }
                $('span.count', this).html('&nbsp;');
            })
            // hide notifications
            $('html').click(function () {
                $('.noti-content').hide();
            })
            // update notification
            function updateNotification() {
                $('#notiContent').empty();
                $('#notiContent').append($('<li>Loading...</li>'));
                $.ajax({
                    type: 'GET',
                    url: '/main/GetNotificationEvents',
                    success: function (response) {
                        $('#notiContent').empty();
                        if (response.length == 0) {
                            $('#notiContent').append($('<li>No data available</li>'));
                        }


                        $.each(response, function (index, value) {
                            function dtConvFromJSON(value) {
                                data = value.StartTime;
                                if (data == null) return '1/1/1950';
                                var r = /\/Date\(([0-9]+)\)\//gi
                                var matches = data.match(r);
                                if (matches == null) return '1/1/1950';
                                var result = matches.toString().substring(6, 19);
                                var epochMilliseconds = result.replace(
                                /^\/Date\(([0-9]+)([+-][0-9]{4})?\)\/$/,
                                '$1');
                                var b = new Date(parseInt(epochMilliseconds));
                                var c = new Date(b.toString());
                                var curr_date = c.getDate();
                                var curr_month = c.getMonth() + 1;
                                var curr_year = c.getFullYear();
                                var curr_h = c.getHours();
                                var curr_m = c.getMinutes();
                                var curr_s = c.getSeconds();
                                var curr_offset = c.getTimezoneOffset() / 60
                                var d = curr_month.toString() + '/' + curr_date + '/' + curr_year + " " + curr_h + ':' + curr_m + ':' + curr_s;
                                return d;
                            }
                            var date = dtConvFromJSON(value);
                            $('#notiContent').append($('<li>New event : ' + value.Subject + ' on' + date + ' added</li>'));
                            //console.log(value);
                        });

                    },
                    error: function (error) {
                        console.log(error);
                    }
                })
            }
            // update notification count
            function updateNotificationCount() {
                var count = 0;
                count = parseInt($('span.count').html()) || 0;
                count++;
                $('span.count').html(count);
            }
            // signalr js code for start hub and send receive notification
            var notificationHub = $.connection.notificationHub;
            $.connection.hub.start().done(function () {
                console.log('Notification hub started');
            });
            $.connection.hub.error(function (err) {
                console.log("HUB ERROR : " + err);
            });
            //signalr method for push server message to client
            notificationHub.client.notify = function (message) {
                if (message && message.toLowerCase() == "added") {
                    updateNotificationCount();
                }
            }
        })
    </script>
    @RenderSection("Scripts", false)
</body>

</html>

ValidationSample/ValidationSample/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="background-image : url(/Content/img/MainLayout.jpg)">
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: rgba(255,255,255,0.5);" data-target="#myNavbar">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Home", "MainView", "Main", new { area = "" }, new { style = "color:green;", @class = "navbar-brand" })
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                

            </div>
            @if (Session["Id"] != null && Session["IsValid2FA"] != null && Convert.ToBoolean(Session["IsValid2FA"]))
            {
                <div class="collapse navbar-collapse " id="myNavbar">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Events", "GetAllEvents", "Main", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("TestSuite", "GetAllTestSuites", "TestSuite", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("TestcaseLog", "GetAllTestcaseLogs", "Main", new { area = "" }, new { @class = "navbar-brand" })
                        @*<span style="padding-left:800px; color: grey" class="navbar-brand">
                        @Html.ActionLink("Logout", "LogOut", "Home", new { style="color:grey;" })
                    </span>*@
                        <li class="w3-dropdown-hover w3-hide-small">
                            <button class="w3-padding-large w3-button" title="More" style="padding-left:300px; color: green; text-align:right"><b>@Session["Id"]</b> <i class="fa fa-caret-down" style="color: grey;align-content:flex-end"></i></button>
                            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                                @Html.ActionLink("Logout", "LogOut", "Home", new { @class = "w3-bar-item w3-button", style = "color:green;" })

                            </div>
                        </li>
                    </ul>
                </div>

            }
           
        </div>
    </div>

    <div class="body-content">
        <hr />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Validation</p>
        </footer>
    </div>

    
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ValidationSample/ValidationSample/Views/Shared/_Layout_Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Validation - Start Validating Now</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- Custom Fonts -->
    <link href="~/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">   
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    
    <!-- Plugin CSS -->
    <link href="~/Content/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">
    <!--Custom CSS-->
    <link href="~/Content/css/creative.css" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="~/Content/css/creative.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Start Validating</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="//localhost:33838/Home/Login">Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    @RenderBody();
    <!-- jQuery -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="~/Content/vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="~/Content/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Theme JavaScript -->
    <script src="~/Scripts/js/creative.min.js"></script>
</body>
</html>